### ISSUE TITLE
Cannot claim horses

### ISSUE THREAD

**Issue by mvcninja** [Xibalba/ZHorse#4]
/zh claim command just gives me message 'You have reached your claim limit' regardless of the settings in config.yml

**Comment by Zedd7** [comment]
Make sure that the group names defined in the config match group names defined in your permission plugin.

If you have set something like this for a specific player who should be able to claim 10 horses : 

```
Groups:

    vip:

        color: <red>

        color-bypass: false

        claims-limit: 10
```

Then this player should belong to the permission group "vip" defined with PermissionBukkit/PermissionEx/...
